CREATE TABLE IF NOT EXISTS guests (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    fullName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    nationalID VARCHAR(255) NOT NULL,
    nationality VARCHAR(255) NOT NULL,
    countryFlag VARCHAR(255) NOT NULL
);
